DROP TABLE IF EXISTS `phpcms_ysqgk`;
CREATE TABLE `phpcms_ysqgk` (
  `ysqgkid` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `siteid` smallint(5) unsigned DEFAULT '0',
  `typeid` smallint(5) unsigned NOT NULL DEFAULT '0',
  `ysqgktype` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `xinxifangshi` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `huoqufangshi` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `name` varchar(50) NOT NULL DEFAULT '',
  `lianxiren` varchar(50) NOT NULL DEFAULT '',
  `frdaibiao` varchar(50) NOT NULL DEFAULT '',
  `bh` varchar(20) NOT NULL DEFAULT '',
  `pass` varchar(50) NOT NULL DEFAULT '',
  `title` varchar(200) NOT NULL DEFAULT '',
  `danwei` varchar(200) NOT NULL DEFAULT '',
  `zhizhao` varchar(200) NOT NULL DEFAULT '',
  `zzjg` varchar(200) NOT NULL DEFAULT '',
  `zhengjianming` varchar(200) NOT NULL DEFAULT '',
  `zhengjianhao` varchar(200) NOT NULL DEFAULT '',
  `dizhi` varchar(200) NOT NULL DEFAULT '',
  `dizhib` varchar(200) NOT NULL DEFAULT '',
  `youbian` varchar(200) NOT NULL DEFAULT '',
  `youbianb` varchar(200) NOT NULL DEFAULT '',
  `gsmz` varchar(200) NOT NULL DEFAULT '',
  `tel` varchar(19) NOT NULL DEFAULT '',
  `telb` varchar(19) NOT NULL DEFAULT '',
  `fax` varchar(19) NOT NULL DEFAULT '',
  `faxb` varchar(19) NOT NULL DEFAULT '',
  `ip` varchar(19) NOT NULL DEFAULT '',
  `content` text NOT NULL,
  `yongtu` text NOT NULL,
  `email` varchar(60) NOT NULL DEFAULT '',
  `emailb` varchar(60) NOT NULL DEFAULT '',
  `elite` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `ps` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `passed` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `addtime` int(10) unsigned NOT NULL DEFAULT '0',
  `listorder` smallint(5) unsigned NOT NULL DEFAULT '0',
  `hftime` int(10) unsigned NOT NULL DEFAULT '0',  PRIMARY KEY (`ysqgkid`),
  `hgcontent`  text NOT NULL,
  KEY `typeid` (`typeid`,`passed`,`ysqgkid`)
) TYPE=MyISAM;