DROP TABLE IF EXISTS `phpcms_yijianzhengji`;
CREATE TABLE `phpcms_yijianzhengji` (
  `yijianzhengjiid` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `siteid` smallint(5) unsigned DEFAULT '0',
  `typeid` smallint(5) unsigned NOT NULL DEFAULT '0',
  `yijianzhengjitype` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `name` varchar(50) NOT NULL DEFAULT '',
  `bh` varchar(20) NOT NULL DEFAULT '',
  `pass` varchar(50) NOT NULL DEFAULT '',
  `title` varchar(200) NOT NULL DEFAULT '',
  `gsmz` varchar(200) NOT NULL DEFAULT '',
  `tel` varchar(19) NOT NULL DEFAULT '',
  `fax` varchar(19) NOT NULL DEFAULT '',
  `ip` varchar(19) NOT NULL DEFAULT '',
  `content` text NOT NULL,
  `email` varchar(60) NOT NULL DEFAULT '',
  `elite` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `ps` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `passed` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `addtime` int(10) unsigned NOT NULL DEFAULT '0',
  `listorder` smallint(5) unsigned NOT NULL DEFAULT '0',
  `hftime` int(10) unsigned NOT NULL DEFAULT '0',  PRIMARY KEY (`yijianzhengjiid`),
  `hgcontent`  text NOT NULL,
  KEY `typeid` (`typeid`,`passed`,`yijianzhengjiid`)
) TYPE=MyISAM;